apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-app
  template:
    metadata:
      labels:
        app: bookstore-app
    spec:
      containers:
        - name: bookstore-app
          image: adrielnascimento/bookstore:1.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          # Ajustando as probes para dar mais tempo à aplicação
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90  # Aumentado para dar mais tempo
            periodSeconds: 30
            timeoutSeconds: 5        # Adicionado timeout
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 45  # Aumentado para dar mais tempo
            periodSeconds: 10
            timeoutSeconds: 5        # Adicionado timeout