apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Se estiver usando AWS
spec:
  selector:
    app: bookstore
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer